# Generated by Django 4.1.5 on 2023-01-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='Engineer',
        ),
    ]
    