# Generated by Django 4.1.5 on 2023-01-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
