# Generated by Django 4.1.5 on 2023-02-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_phone', models.CharField(max_length=10)),
                ('b_email', models.EmailField(max_length=254)),
                ('b_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('b_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.services')),
            ],
        ),
    ]
